FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app

COPY PoCAuthJWT.sln .
COPY src/Domain/Domain.csproj src/Domain/
COPY src/Application/Application.csproj src/Application/
COPY src/Infrastructure/Infrastructure.csproj src/Infrastructure/
COPY src/Api/Api.csproj src/Api/
COPY src/Backoffice/Backoffice.csproj src/Backoffice/

RUN dotnet restore src/Backoffice/Backoffice.csproj

COPY src/ src/

RUN dotnet publish src/Backoffice/Backoffice.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /out .

ENTRYPOINT ["dotnet", "Backoffice.dll"]
